### ISSUE TITLE
Robinhood 2FA

### ISSUE THREAD

**Issue by aleph0ne** [andrewstuart/go-robinhood#27]
Anyone have a solution for this? Robinhood now requires 2FA (two-factor authentication) and this API library returns an error.

`Get "https://nummus.robinhood.com/accounts/": Two Factor Auth code required and not supplied`

cc @andrewstuart @MitchK

**Comment by andrewstuart** [comment]
I believe that you may need to implement a check for that error, and then through presumably SMS, have a way in your automation to update your 2fa code on the TokenSource: https://pkg.go.dev/github.com/andrewstuart/go-robinhood/v2#OAuth. The next Dial attempt, once that's triggered to send to you by the first login, then updated via reading stdin (or whatever), I believe you should be good. It's been a *long* time since I've tested that, though.

**Comment by andrewstuart** [comment]
Feel free to reopen if you still have the issue.
